# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table
content: 
{{ .Module }}

{{ .Inputs }}

{{ .Outputs }}

# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: docs/header.md

# see: https://terraform-docs.io/user-guide/configuration/footer-from
footer-from: docs/footer.md